name: kp_directory
description: Collection of useful functions for Directory objects.
author: Kasper Peulen <kasperpeulen@gmail.com>
homepage: https://github.com/kasperpeulen/kp_directory.dart
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  path: '^1.3.9'
dev_dependencies:
  test: ^0.12.6+1
  grinder: ^0.8.0+1
  coverage: ^0.7.2
  dart_dev: ^1.0.5

